/********************************************************************************
** Form generated from reading UI file 'ImageGenerationDialog.ui'
**
** Created by: Qt User Interface Compiler version 5.6.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_IMAGEGENERATIONDIALOG_H
#define UI_IMAGEGENERATIONDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>

QT_BEGIN_NAMESPACE

class Ui_ImageGenerationDialog
{
public:
    QPushButton *pushButtonOK;
    QPushButton *pushButtonCancel;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *lineEditCGADirectory;
    QPushButton *pushButtonCGADirectory;
    QLineEdit *lineEditOutputDirectory;
    QPushButton *pushButtonOutputDirectory;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *lineEditImageSize;
    QLabel *label_6;
    QLineEdit *lineEditCameraDistance;
    QLabel *label_7;
    QLineEdit *lineEditXrotMin;
    QLineEdit *lineEditXrotMax;
    QLabel *label_8;
    QLabel *label_9;
    QLineEdit *lineEditYrotMin;
    QLineEdit *lineEditYrotMax;
    QLabel *label_10;
    QLineEdit *lineEditFovMax;
    QLineEdit *lineEditFovMin;
    QLabel *label_11;
    QLabel *label_12;
    QGroupBox *groupBox;
    QCheckBox *checkBoxModifyImage;
    QLineEdit *lineEditLineWidthMax;
    QLabel *label_13;
    QLineEdit *lineEditLineWidthMin;
    QLabel *label_14;
    QCheckBox *checkBoxEdgeNoise;
    QLineEdit *lineEditEdgeNoiseMax;
    QLabel *label_15;
    QLineEdit *lineEditZrotMax;
    QLabel *label_16;
    QLineEdit *lineEditZrotMin;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLineEdit *lineEditXrotSample;
    QLabel *label_21;
    QLabel *label_23;
    QLineEdit *lineEditYrotSample;
    QLineEdit *lineEditZrotSample;
    QLabel *label_25;
    QLineEdit *lineEditFovSample;
    QLabel *label_27;
    QLineEdit *lineEditTotalNumImages;
    QLabel *label_29;
    QLabel *label_31;
    QLineEdit *lineEditXMin;
    QLineEdit *lineEditXMax;
    QLineEdit *lineEditYMin;
    QLabel *label_32;
    QLineEdit *lineEditYMax;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLineEdit *lineEditXSample;
    QLabel *label_37;
    QLineEdit *lineEditYSample;
    QLabel *label_38;
    QRadioButton *radioButtonRenderSilhouette;
    QRadioButton *radioButtonRenderLine;
    QLabel *label_39;
    QCheckBox *checkBoxDiscardTopFaceVisible;
    QCheckBox *checkBoxDiscardBottomFaceVisible;
    QCheckBox *checkBoxDiscardTooBig;
    QLineEdit *lineEditOXMax;
    QLabel *label_40;
    QLineEdit *lineEditOXSample;
    QLabel *label_41;
    QLabel *label_42;
    QLineEdit *lineEditOXMin;
    QLabel *label_43;
    QLabel *label_44;
    QLineEdit *lineEditOYMax;
    QLineEdit *lineEditOYSample;
    QLineEdit *lineEditOYMin;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLineEdit *lineEditPMSample;

    void setupUi(QDialog *ImageGenerationDialog)
    {
        if (ImageGenerationDialog->objectName().isEmpty())
            ImageGenerationDialog->setObjectName(QStringLiteral("ImageGenerationDialog"));
        ImageGenerationDialog->resize(579, 702);
        pushButtonOK = new QPushButton(ImageGenerationDialog);
        pushButtonOK->setObjectName(QStringLiteral("pushButtonOK"));
        pushButtonOK->setGeometry(QRect(360, 660, 91, 31));
        pushButtonCancel = new QPushButton(ImageGenerationDialog);
        pushButtonCancel->setObjectName(QStringLiteral("pushButtonCancel"));
        pushButtonCancel->setGeometry(QRect(460, 660, 91, 31));
        label = new QLabel(ImageGenerationDialog);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 20, 91, 16));
        label_2 = new QLabel(ImageGenerationDialog);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 50, 91, 16));
        lineEditCGADirectory = new QLineEdit(ImageGenerationDialog);
        lineEditCGADirectory->setObjectName(QStringLiteral("lineEditCGADirectory"));
        lineEditCGADirectory->setGeometry(QRect(140, 20, 381, 20));
        pushButtonCGADirectory = new QPushButton(ImageGenerationDialog);
        pushButtonCGADirectory->setObjectName(QStringLiteral("pushButtonCGADirectory"));
        pushButtonCGADirectory->setGeometry(QRect(530, 20, 31, 23));
        lineEditOutputDirectory = new QLineEdit(ImageGenerationDialog);
        lineEditOutputDirectory->setObjectName(QStringLiteral("lineEditOutputDirectory"));
        lineEditOutputDirectory->setGeometry(QRect(140, 50, 381, 20));
        pushButtonOutputDirectory = new QPushButton(ImageGenerationDialog);
        pushButtonOutputDirectory->setObjectName(QStringLiteral("pushButtonOutputDirectory"));
        pushButtonOutputDirectory->setGeometry(QRect(530, 50, 31, 23));
        label_4 = new QLabel(ImageGenerationDialog);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(198, 80, 16, 21));
        label_5 = new QLabel(ImageGenerationDialog);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 80, 91, 16));
        lineEditImageSize = new QLineEdit(ImageGenerationDialog);
        lineEditImageSize->setObjectName(QStringLiteral("lineEditImageSize"));
        lineEditImageSize->setGeometry(QRect(140, 80, 51, 20));
        label_6 = new QLabel(ImageGenerationDialog);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(20, 110, 91, 16));
        lineEditCameraDistance = new QLineEdit(ImageGenerationDialog);
        lineEditCameraDistance->setObjectName(QStringLiteral("lineEditCameraDistance"));
        lineEditCameraDistance->setGeometry(QRect(140, 110, 51, 20));
        label_7 = new QLabel(ImageGenerationDialog);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(20, 140, 91, 16));
        lineEditXrotMin = new QLineEdit(ImageGenerationDialog);
        lineEditXrotMin->setObjectName(QStringLiteral("lineEditXrotMin"));
        lineEditXrotMin->setGeometry(QRect(140, 140, 81, 20));
        lineEditXrotMax = new QLineEdit(ImageGenerationDialog);
        lineEditXrotMax->setObjectName(QStringLiteral("lineEditXrotMax"));
        lineEditXrotMax->setGeometry(QRect(240, 140, 81, 20));
        label_8 = new QLabel(ImageGenerationDialog);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(226, 140, 16, 16));
        label_9 = new QLabel(ImageGenerationDialog);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 170, 91, 16));
        lineEditYrotMin = new QLineEdit(ImageGenerationDialog);
        lineEditYrotMin->setObjectName(QStringLiteral("lineEditYrotMin"));
        lineEditYrotMin->setGeometry(QRect(140, 170, 81, 20));
        lineEditYrotMax = new QLineEdit(ImageGenerationDialog);
        lineEditYrotMax->setObjectName(QStringLiteral("lineEditYrotMax"));
        lineEditYrotMax->setGeometry(QRect(240, 170, 81, 20));
        label_10 = new QLabel(ImageGenerationDialog);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(226, 170, 16, 16));
        lineEditFovMax = new QLineEdit(ImageGenerationDialog);
        lineEditFovMax->setObjectName(QStringLiteral("lineEditFovMax"));
        lineEditFovMax->setGeometry(QRect(240, 230, 81, 20));
        lineEditFovMin = new QLineEdit(ImageGenerationDialog);
        lineEditFovMin->setObjectName(QStringLiteral("lineEditFovMin"));
        lineEditFovMin->setGeometry(QRect(140, 230, 81, 20));
        label_11 = new QLabel(ImageGenerationDialog);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(20, 230, 91, 16));
        label_12 = new QLabel(ImageGenerationDialog);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(226, 230, 16, 16));
        groupBox = new QGroupBox(ImageGenerationDialog);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(20, 530, 541, 111));
        checkBoxModifyImage = new QCheckBox(groupBox);
        checkBoxModifyImage->setObjectName(QStringLiteral("checkBoxModifyImage"));
        checkBoxModifyImage->setGeometry(QRect(40, 20, 141, 17));
        lineEditLineWidthMax = new QLineEdit(groupBox);
        lineEditLineWidthMax->setObjectName(QStringLiteral("lineEditLineWidthMax"));
        lineEditLineWidthMax->setGeometry(QRect(230, 50, 51, 20));
        label_13 = new QLabel(groupBox);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(40, 50, 91, 16));
        lineEditLineWidthMin = new QLineEdit(groupBox);
        lineEditLineWidthMin->setObjectName(QStringLiteral("lineEditLineWidthMin"));
        lineEditLineWidthMin->setGeometry(QRect(160, 50, 51, 20));
        label_14 = new QLabel(groupBox);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(215, 50, 16, 16));
        checkBoxEdgeNoise = new QCheckBox(groupBox);
        checkBoxEdgeNoise->setObjectName(QStringLiteral("checkBoxEdgeNoise"));
        checkBoxEdgeNoise->setGeometry(QRect(40, 80, 91, 17));
        lineEditEdgeNoiseMax = new QLineEdit(groupBox);
        lineEditEdgeNoiseMax->setObjectName(QStringLiteral("lineEditEdgeNoiseMax"));
        lineEditEdgeNoiseMax->setGeometry(QRect(160, 80, 51, 20));
        label_15 = new QLabel(groupBox);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(216, 80, 16, 21));
        lineEditZrotMax = new QLineEdit(ImageGenerationDialog);
        lineEditZrotMax->setObjectName(QStringLiteral("lineEditZrotMax"));
        lineEditZrotMax->setGeometry(QRect(240, 200, 81, 20));
        label_16 = new QLabel(ImageGenerationDialog);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(20, 200, 101, 16));
        lineEditZrotMin = new QLineEdit(ImageGenerationDialog);
        lineEditZrotMin->setObjectName(QStringLiteral("lineEditZrotMin"));
        lineEditZrotMin->setGeometry(QRect(140, 200, 81, 20));
        label_17 = new QLabel(ImageGenerationDialog);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(330, 140, 41, 21));
        label_18 = new QLabel(ImageGenerationDialog);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(330, 170, 41, 21));
        label_19 = new QLabel(ImageGenerationDialog);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(330, 200, 41, 21));
        label_20 = new QLabel(ImageGenerationDialog);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(330, 230, 41, 21));
        lineEditXrotSample = new QLineEdit(ImageGenerationDialog);
        lineEditXrotSample->setObjectName(QStringLiteral("lineEditXrotSample"));
        lineEditXrotSample->setGeometry(QRect(460, 140, 31, 20));
        label_21 = new QLabel(ImageGenerationDialog);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(410, 140, 41, 21));
        label_23 = new QLabel(ImageGenerationDialog);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(410, 170, 41, 21));
        lineEditYrotSample = new QLineEdit(ImageGenerationDialog);
        lineEditYrotSample->setObjectName(QStringLiteral("lineEditYrotSample"));
        lineEditYrotSample->setGeometry(QRect(460, 170, 31, 20));
        lineEditZrotSample = new QLineEdit(ImageGenerationDialog);
        lineEditZrotSample->setObjectName(QStringLiteral("lineEditZrotSample"));
        lineEditZrotSample->setGeometry(QRect(460, 200, 31, 20));
        label_25 = new QLabel(ImageGenerationDialog);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(410, 200, 41, 21));
        lineEditFovSample = new QLineEdit(ImageGenerationDialog);
        lineEditFovSample->setObjectName(QStringLiteral("lineEditFovSample"));
        lineEditFovSample->setGeometry(QRect(460, 230, 31, 20));
        label_27 = new QLabel(ImageGenerationDialog);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(410, 230, 41, 21));
        lineEditTotalNumImages = new QLineEdit(ImageGenerationDialog);
        lineEditTotalNumImages->setObjectName(QStringLiteral("lineEditTotalNumImages"));
        lineEditTotalNumImages->setEnabled(false);
        lineEditTotalNumImages->setGeometry(QRect(190, 410, 81, 20));
        label_29 = new QLabel(ImageGenerationDialog);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(20, 410, 171, 16));
        label_31 = new QLabel(ImageGenerationDialog);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(20, 320, 91, 16));
        lineEditXMin = new QLineEdit(ImageGenerationDialog);
        lineEditXMin->setObjectName(QStringLiteral("lineEditXMin"));
        lineEditXMin->setGeometry(QRect(140, 320, 81, 20));
        lineEditXMax = new QLineEdit(ImageGenerationDialog);
        lineEditXMax->setObjectName(QStringLiteral("lineEditXMax"));
        lineEditXMax->setGeometry(QRect(240, 320, 81, 20));
        lineEditYMin = new QLineEdit(ImageGenerationDialog);
        lineEditYMin->setObjectName(QStringLiteral("lineEditYMin"));
        lineEditYMin->setGeometry(QRect(140, 350, 81, 20));
        label_32 = new QLabel(ImageGenerationDialog);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(20, 350, 91, 16));
        lineEditYMax = new QLineEdit(ImageGenerationDialog);
        lineEditYMax->setObjectName(QStringLiteral("lineEditYMax"));
        lineEditYMax->setGeometry(QRect(240, 350, 81, 20));
        label_33 = new QLabel(ImageGenerationDialog);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(226, 200, 16, 16));
        label_34 = new QLabel(ImageGenerationDialog);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(226, 320, 16, 16));
        label_35 = new QLabel(ImageGenerationDialog);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(226, 350, 16, 16));
        label_36 = new QLabel(ImageGenerationDialog);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(410, 320, 41, 21));
        lineEditXSample = new QLineEdit(ImageGenerationDialog);
        lineEditXSample->setObjectName(QStringLiteral("lineEditXSample"));
        lineEditXSample->setGeometry(QRect(460, 320, 31, 20));
        label_37 = new QLabel(ImageGenerationDialog);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(410, 350, 41, 21));
        lineEditYSample = new QLineEdit(ImageGenerationDialog);
        lineEditYSample->setObjectName(QStringLiteral("lineEditYSample"));
        lineEditYSample->setGeometry(QRect(460, 350, 31, 20));
        label_38 = new QLabel(ImageGenerationDialog);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(20, 440, 91, 16));
        radioButtonRenderSilhouette = new QRadioButton(ImageGenerationDialog);
        radioButtonRenderSilhouette->setObjectName(QStringLiteral("radioButtonRenderSilhouette"));
        radioButtonRenderSilhouette->setGeometry(QRect(140, 440, 82, 17));
        radioButtonRenderLine = new QRadioButton(ImageGenerationDialog);
        radioButtonRenderLine->setObjectName(QStringLiteral("radioButtonRenderLine"));
        radioButtonRenderLine->setGeometry(QRect(250, 440, 82, 17));
        label_39 = new QLabel(ImageGenerationDialog);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(20, 470, 91, 16));
        checkBoxDiscardTopFaceVisible = new QCheckBox(ImageGenerationDialog);
        checkBoxDiscardTopFaceVisible->setObjectName(QStringLiteral("checkBoxDiscardTopFaceVisible"));
        checkBoxDiscardTopFaceVisible->setGeometry(QRect(140, 500, 141, 17));
        checkBoxDiscardBottomFaceVisible = new QCheckBox(ImageGenerationDialog);
        checkBoxDiscardBottomFaceVisible->setObjectName(QStringLiteral("checkBoxDiscardBottomFaceVisible"));
        checkBoxDiscardBottomFaceVisible->setGeometry(QRect(310, 500, 141, 17));
        checkBoxDiscardTooBig = new QCheckBox(ImageGenerationDialog);
        checkBoxDiscardTooBig->setObjectName(QStringLiteral("checkBoxDiscardTooBig"));
        checkBoxDiscardTooBig->setGeometry(QRect(140, 470, 141, 17));
        lineEditOXMax = new QLineEdit(ImageGenerationDialog);
        lineEditOXMax->setObjectName(QStringLiteral("lineEditOXMax"));
        lineEditOXMax->setGeometry(QRect(240, 260, 81, 20));
        label_40 = new QLabel(ImageGenerationDialog);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(226, 260, 16, 16));
        lineEditOXSample = new QLineEdit(ImageGenerationDialog);
        lineEditOXSample->setObjectName(QStringLiteral("lineEditOXSample"));
        lineEditOXSample->setGeometry(QRect(460, 260, 31, 20));
        label_41 = new QLabel(ImageGenerationDialog);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(20, 260, 91, 16));
        label_42 = new QLabel(ImageGenerationDialog);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(410, 260, 41, 21));
        lineEditOXMin = new QLineEdit(ImageGenerationDialog);
        lineEditOXMin->setObjectName(QStringLiteral("lineEditOXMin"));
        lineEditOXMin->setGeometry(QRect(140, 260, 81, 20));
        label_43 = new QLabel(ImageGenerationDialog);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(226, 290, 16, 16));
        label_44 = new QLabel(ImageGenerationDialog);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(410, 290, 41, 21));
        lineEditOYMax = new QLineEdit(ImageGenerationDialog);
        lineEditOYMax->setObjectName(QStringLiteral("lineEditOYMax"));
        lineEditOYMax->setGeometry(QRect(240, 290, 81, 20));
        lineEditOYSample = new QLineEdit(ImageGenerationDialog);
        lineEditOYSample->setObjectName(QStringLiteral("lineEditOYSample"));
        lineEditOYSample->setGeometry(QRect(460, 290, 31, 20));
        lineEditOYMin = new QLineEdit(ImageGenerationDialog);
        lineEditOYMin->setObjectName(QStringLiteral("lineEditOYMin"));
        lineEditOYMin->setGeometry(QRect(140, 290, 81, 20));
        label_45 = new QLabel(ImageGenerationDialog);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(20, 290, 91, 16));
        label_46 = new QLabel(ImageGenerationDialog);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(410, 380, 41, 21));
        label_47 = new QLabel(ImageGenerationDialog);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(20, 380, 91, 16));
        lineEditPMSample = new QLineEdit(ImageGenerationDialog);
        lineEditPMSample->setObjectName(QStringLiteral("lineEditPMSample"));
        lineEditPMSample->setGeometry(QRect(460, 380, 31, 20));
        QWidget::setTabOrder(lineEditCGADirectory, pushButtonCGADirectory);
        QWidget::setTabOrder(pushButtonCGADirectory, lineEditOutputDirectory);
        QWidget::setTabOrder(lineEditOutputDirectory, pushButtonOutputDirectory);
        QWidget::setTabOrder(pushButtonOutputDirectory, lineEditImageSize);
        QWidget::setTabOrder(lineEditImageSize, lineEditCameraDistance);
        QWidget::setTabOrder(lineEditCameraDistance, lineEditXrotMin);
        QWidget::setTabOrder(lineEditXrotMin, lineEditXrotMax);
        QWidget::setTabOrder(lineEditXrotMax, lineEditXrotSample);
        QWidget::setTabOrder(lineEditXrotSample, lineEditYrotMin);
        QWidget::setTabOrder(lineEditYrotMin, lineEditYrotMax);
        QWidget::setTabOrder(lineEditYrotMax, lineEditYrotSample);
        QWidget::setTabOrder(lineEditYrotSample, lineEditZrotMin);
        QWidget::setTabOrder(lineEditZrotMin, lineEditZrotMax);
        QWidget::setTabOrder(lineEditZrotMax, lineEditZrotSample);
        QWidget::setTabOrder(lineEditZrotSample, lineEditFovMin);
        QWidget::setTabOrder(lineEditFovMin, lineEditFovMax);
        QWidget::setTabOrder(lineEditFovMax, lineEditFovSample);
        QWidget::setTabOrder(lineEditFovSample, lineEditOXMin);
        QWidget::setTabOrder(lineEditOXMin, lineEditOXMax);
        QWidget::setTabOrder(lineEditOXMax, lineEditOXSample);
        QWidget::setTabOrder(lineEditOXSample, lineEditOYMin);
        QWidget::setTabOrder(lineEditOYMin, lineEditOYMax);
        QWidget::setTabOrder(lineEditOYMax, lineEditOYSample);
        QWidget::setTabOrder(lineEditOYSample, lineEditXMin);
        QWidget::setTabOrder(lineEditXMin, lineEditXMax);
        QWidget::setTabOrder(lineEditXMax, lineEditXSample);
        QWidget::setTabOrder(lineEditXSample, lineEditYMin);
        QWidget::setTabOrder(lineEditYMin, lineEditYMax);
        QWidget::setTabOrder(lineEditYMax, lineEditYSample);
        QWidget::setTabOrder(lineEditYSample, lineEditTotalNumImages);
        QWidget::setTabOrder(lineEditTotalNumImages, radioButtonRenderSilhouette);
        QWidget::setTabOrder(radioButtonRenderSilhouette, radioButtonRenderLine);
        QWidget::setTabOrder(radioButtonRenderLine, checkBoxDiscardTooBig);
        QWidget::setTabOrder(checkBoxDiscardTooBig, checkBoxDiscardTopFaceVisible);
        QWidget::setTabOrder(checkBoxDiscardTopFaceVisible, checkBoxDiscardBottomFaceVisible);
        QWidget::setTabOrder(checkBoxDiscardBottomFaceVisible, checkBoxModifyImage);
        QWidget::setTabOrder(checkBoxModifyImage, lineEditLineWidthMin);
        QWidget::setTabOrder(lineEditLineWidthMin, lineEditLineWidthMax);
        QWidget::setTabOrder(lineEditLineWidthMax, checkBoxEdgeNoise);
        QWidget::setTabOrder(checkBoxEdgeNoise, lineEditEdgeNoiseMax);
        QWidget::setTabOrder(lineEditEdgeNoiseMax, pushButtonOK);
        QWidget::setTabOrder(pushButtonOK, pushButtonCancel);

        retranslateUi(ImageGenerationDialog);

        QMetaObject::connectSlotsByName(ImageGenerationDialog);
    } // setupUi

    void retranslateUi(QDialog *ImageGenerationDialog)
    {
        ImageGenerationDialog->setWindowTitle(QApplication::translate("ImageGenerationDialog", "ImageGenerationDialog", 0));
        pushButtonOK->setText(QApplication::translate("ImageGenerationDialog", "OK", 0));
        pushButtonCancel->setText(QApplication::translate("ImageGenerationDialog", "Cancel", 0));
        label->setText(QApplication::translate("ImageGenerationDialog", "CGA directory:", 0));
        label_2->setText(QApplication::translate("ImageGenerationDialog", "Output directory:", 0));
        pushButtonCGADirectory->setText(QApplication::translate("ImageGenerationDialog", "...", 0));
        pushButtonOutputDirectory->setText(QApplication::translate("ImageGenerationDialog", "...", 0));
        label_4->setText(QApplication::translate("ImageGenerationDialog", "px", 0));
        label_5->setText(QApplication::translate("ImageGenerationDialog", "Image size:", 0));
        label_6->setText(QApplication::translate("ImageGenerationDialog", "Camera distance:", 0));
        label_7->setText(QApplication::translate("ImageGenerationDialog", "Rot around X axis:", 0));
        label_8->setText(QApplication::translate("ImageGenerationDialog", "~", 0));
        label_9->setText(QApplication::translate("ImageGenerationDialog", "Rot around Y axis:", 0));
        label_10->setText(QApplication::translate("ImageGenerationDialog", "~", 0));
        label_11->setText(QApplication::translate("ImageGenerationDialog", "Field of view:", 0));
        label_12->setText(QApplication::translate("ImageGenerationDialog", "~", 0));
        groupBox->setTitle(QApplication::translate("ImageGenerationDialog", "Image modification", 0));
        checkBoxModifyImage->setText(QApplication::translate("ImageGenerationDialog", "Modify rendered image", 0));
        label_13->setText(QApplication::translate("ImageGenerationDialog", "Line width:", 0));
        label_14->setText(QApplication::translate("ImageGenerationDialog", "~", 0));
        checkBoxEdgeNoise->setText(QApplication::translate("ImageGenerationDialog", "Edge noise", 0));
        label_15->setText(QApplication::translate("ImageGenerationDialog", "%", 0));
        label_16->setText(QApplication::translate("ImageGenerationDialog", "Rot around Z axis:", 0));
        label_17->setText(QApplication::translate("ImageGenerationDialog", "degree", 0));
        label_18->setText(QApplication::translate("ImageGenerationDialog", "degree", 0));
        label_19->setText(QApplication::translate("ImageGenerationDialog", "degree", 0));
        label_20->setText(QApplication::translate("ImageGenerationDialog", "degree", 0));
        label_21->setText(QApplication::translate("ImageGenerationDialog", "Sample", 0));
        label_23->setText(QApplication::translate("ImageGenerationDialog", "Sample", 0));
        label_25->setText(QApplication::translate("ImageGenerationDialog", "Sample", 0));
        label_27->setText(QApplication::translate("ImageGenerationDialog", "Sample", 0));
        label_29->setText(QApplication::translate("ImageGenerationDialog", "The total number of images will be", 0));
        label_31->setText(QApplication::translate("ImageGenerationDialog", "X coordinates:", 0));
        label_32->setText(QApplication::translate("ImageGenerationDialog", "Y coordinates:", 0));
        label_33->setText(QApplication::translate("ImageGenerationDialog", "~", 0));
        label_34->setText(QApplication::translate("ImageGenerationDialog", "~", 0));
        label_35->setText(QApplication::translate("ImageGenerationDialog", "~", 0));
        label_36->setText(QApplication::translate("ImageGenerationDialog", "Sample", 0));
        label_37->setText(QApplication::translate("ImageGenerationDialog", "Sample", 0));
        label_38->setText(QApplication::translate("ImageGenerationDialog", "Rendering option:", 0));
        radioButtonRenderSilhouette->setText(QApplication::translate("ImageGenerationDialog", "Silhouette", 0));
        radioButtonRenderLine->setText(QApplication::translate("ImageGenerationDialog", "Line", 0));
        label_39->setText(QApplication::translate("ImageGenerationDialog", "Discard:", 0));
        checkBoxDiscardTopFaceVisible->setText(QApplication::translate("ImageGenerationDialog", "If the top face is visible", 0));
        checkBoxDiscardBottomFaceVisible->setText(QApplication::translate("ImageGenerationDialog", "If the bottom face is visible", 0));
        checkBoxDiscardTooBig->setText(QApplication::translate("ImageGenerationDialog", "If the building is too big", 0));
        label_40->setText(QApplication::translate("ImageGenerationDialog", "~", 0));
        label_41->setText(QApplication::translate("ImageGenerationDialog", "Ox:", 0));
        label_42->setText(QApplication::translate("ImageGenerationDialog", "Sample", 0));
        label_43->setText(QApplication::translate("ImageGenerationDialog", "~", 0));
        label_44->setText(QApplication::translate("ImageGenerationDialog", "Sample", 0));
        label_45->setText(QApplication::translate("ImageGenerationDialog", "Oy:", 0));
        label_46->setText(QApplication::translate("ImageGenerationDialog", "Sample", 0));
        label_47->setText(QApplication::translate("ImageGenerationDialog", "PM Parameters:", 0));
    } // retranslateUi

};

namespace Ui {
    class ImageGenerationDialog: public Ui_ImageGenerationDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_IMAGEGENERATIONDIALOG_H
